### ISSUE TITLE
LogExporterApp JSON/HTTP output using jsonl

### ISSUE THREAD

**Issue by vanhecke** [TechnitiumSoftware/DnsServer#1381]
The LogExporterApp offers event forwarding via HTTPS POST messages which is an excellent & modern way to forward logs to cloud logging platforms.

However the http client is creating sub-optimal payloads that are not natively supported by many of these systems.

Issues:

1. Duplicate data (MessageTemplate and RenderedMessage seem identical) -> Suggest to remove
2. Custom format / nesting offers no value -> Suggest to use jsonl

Current payload example:
```json
[
  {
    "Timestamp": "2025-07-11T16:46:15.4306550Z",
    "Level": "Information",
    "MessageTemplate": "{\"timestamp\":\"2025-07-11T16:46:12.925Z\",\"clientIp\":\"10.13.37.24\",\"protocol\":\"Udp\",\"responseType\":\"Cached\",\"responseCode\":\"NoError\",\"question\":{\"questionName\":\"ocsp.godaddy.com\",\"questionType\":\"A\",\"questionClass\":\"IN\"},\"answers\":[{\"name\":\"ocsp.godaddy.com\",\"recordType\":\"CNAME\",\"recordClass\":\"IN\",\"recordTtl\":3596,\"recordData\":\"ocsp.godaddy.com.akadns.net.\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.22\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.41\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.23\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.24\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.36\",\"dnssecStatus\":\"Insecure\"}]}",
    "RenderedMessage": "{\"timestamp\":\"2025-07-11T16:46:12.925Z\",\"clientIp\":\"10.13.37.24\",\"protocol\":\"Udp\",\"responseType\":\"Cached\",\"responseCode\":\"NoError\",\"question\":{\"questionName\":\"ocsp.godaddy.com\",\"questionType\":\"A\",\"questionClass\":\"IN\"},\"answers\":[{\"name\":\"ocsp.godaddy.com\",\"recordType\":\"CNAME\",\"recordClass\":\"IN\",\"recordTtl\":3596,\"recordData\":\"ocsp.godaddy.com.akadns.net.\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.22\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.41\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.23\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.24\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"ocsp.godaddy.com.akadns.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":56,\"recordData\":\"192.124.249.36\",\"dnssecStatus\":\"Insecure\"}]}"
  },
  {
    "Timestamp": "2025-07-11T16:46:15.4309626Z",
    "Level": "Information",
    "MessageTemplate": "{\"timestamp\":\"2025-07-11T16:46:13.284Z\",\"clientIp\":\"10.13.37.24\",\"protocol\":\"Udp\",\"responseType\":\"Cached\",\"responseCode\":\"NoError\",\"question\":{\"questionName\":\"storage.googleapis.com\",\"questionType\":\"AAAA\",\"questionClass\":\"IN\"},\"answers\":[{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c02::cf\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c09::cf\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c0c::cf\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c07::cf\",\"dnssecStatus\":\"Insecure\"}]}",
    "RenderedMessage": "{\"timestamp\":\"2025-07-11T16:46:13.284Z\",\"clientIp\":\"10.13.37.24\",\"protocol\":\"Udp\",\"responseType\":\"Cached\",\"responseCode\":\"NoError\",\"question\":{\"questionName\":\"storage.googleapis.com\",\"questionType\":\"AAAA\",\"questionClass\":\"IN\"},\"answers\":[{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c02::cf\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c09::cf\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c0c::cf\",\"dnssecStatus\":\"Insecure\"},{\"name\":\"storage.googleapis.com\",\"recordType\":\"AAAA\",\"recordClass\":\"IN\",\"recordTtl\":222,\"recordData\":\"2a00:1450:400c:c07::cf\",\"dnssecStatus\":\"Insecure\"}]}"
  }
]
``` 

The preferred layout would be to use the jsonl format (info: [jsontools.com/what-is-jsonl](https://jsonltools.com/what-is-jsonl) and [jsonlines.org](https://jsonlines.org/)). 
And overall reduce the output.

Suggestion (using jsonl format, and only including "RenderedMessage"):

```json
{"timestamp":"2025-07-11T16:46:12.925Z","clientIp":"10.13.37.24","protocol":"Udp","responseType":"Cached","responseCode":"NoError","question":{"questionName":"ocsp.godaddy.com","questionType":"A","questionClass":"IN"},"answers":[{"name":"ocsp.godaddy.com","recordType":"CNAME","recordClass":"IN","recordTtl":3596,"recordData":"ocsp.godaddy.com.akadns.net.","dnssecStatus":"Insecure"},{"name":"ocsp.godaddy.com.akadns.net","recordType":"A","recordClass":"IN","recordTtl":56,"recordData":"192.124.249.22","dnssecStatus":"Insecure"},{"name":"ocsp.godaddy.com.akadns.net","recordType":"A","recordClass":"IN","recordTtl":56,"recordData":"192.124.249.41","dnssecStatus":"Insecure"},{"name":"ocsp.godaddy.com.akadns.net","recordType":"A","recordClass":"IN","recordTtl":56,"recordData":"192.124.249.23","dnssecStatus":"Insecure"},{"name":"ocsp.godaddy.com.akadns.net","recordType":"A","recordClass":"IN","recordTtl":56,"recordData":"192.124.249.24","dnssecStatus":"Insecure"},{"name":"ocsp.godaddy.com.akadns.net","recordType":"A","recordClass":"IN","recordTtl":56,"recordData":"192.124.249.36","dnssecStatus":"Insecure"}]}
{"timestamp":"2025-07-11T16:46:13.284Z","clientIp":"10.13.37.24","protocol":"Udp","responseType":"Cached","responseCode":"NoError","question":{"questionName":"storage.googleapis.com","questionType":"AAAA","questionClass":"IN"},"answers":[{"name":"storage.googleapis.com","recordType":"AAAA","recordClass":"IN","recordTtl":222,"recordData":"2a00:1450:400c:c02::cf","dnssecStatus":"Insecure"},{"name":"storage.googleapis.com","recordType":"AAAA","recordClass":"IN","recordTtl":222,"recordData":"2a00:1450:400c:c09::cf","dnssecStatus":"Insecure"},{"name":"storage.googleapis.com","recordType":"AAAA","recordClass":"IN","recordTtl":222,"recordData":"2a00:1450:400c:c0c::cf","dnssecStatus":"Insecure"},{"name":"storage.googleapis.com","recordType":"AAAA","recordClass":"IN","recordTtl":222,"recordData":"2a00:1450:400c:c07::cf","dnssecStatus":"Insecure"}]}

```

I wanted to propose this to the contributors before attempting to make the code change myself. Thanks

**Comment by ShreyasZare** [comment]
Thanks for the post. This app was implemented by @zbalkan and I do not have this app in production in any of my setup so not sure how this JSON output is being rendered. There is no such explicit code in the app which generates this JSON output. It seems that the Serilog library which is being used for this is generating this final JSON output. @zbalkan probably has this running in production so he may be in a better position to explain this.

Regarding changing the format, its really not feasible now that the app is being used in production. Also JSONL format seems to be about storing multiple entries per line in a file, however these logs are generated for each DNS request and are sent individually to the server immediately or within few seconds.

**Comment by vanhecke** [comment]
Thanks for your feedback.

> Also JSONL format seems to be about storing multiple entries per line in a file, however these logs are generated for each DNS request and are sent individually to the server immediately or within few seconds.

The app reads up to 1000 logs from a queue, pushes them to the destination, and then sleeps 10 seconds.
https://github.com/TechnitiumSoftware/DnsServer/blob/3a7636ac3b1c221521f4031bb185277bbc85f068/Apps/LogExporterApp/App.cs#L46-L47

So it's *roughly* every 10 seconds. And up to 1000 logs.

**Comment by ShreyasZare** [comment]
> > Also JSONL format seems to be about storing multiple entries per line in a file, however these logs are generated for each DNS request and are sent individually to the server immediately or within few seconds.
> 
> The app reads up to 1000 logs from a queue, pushes them to the destination, and then sleeps 10 seconds.
> 
> [DnsServer/Apps/LogExporterApp/App.cs](https://github.com/TechnitiumSoftware/DnsServer/blob/3a7636ac3b1c221521f4031bb185277bbc85f068/Apps/LogExporterApp/App.cs#L46-L47)
> 
> Lines 46 to 47 in [3a7636a](/TechnitiumSoftware/DnsServer/commit/3a7636ac3b1c221521f4031bb185277bbc85f068)
>  const int QUEUE_TIMER_INTERVAL = 10000; 
>  const int BULK_INSERT_COUNT = 1000; 
> 
> So it's _roughly_ every 10 seconds. And up to 1000 logs.

Yes, the timer runs every 10 sec but if there are more than 1000 logs available, it will keep on sending them in batch of max 1000 logs. It "sleeps" (resets the timer to 10 sec) only when no logs are available. So, it does batching but the uploading task is done with Serilog here which does it individually. Not sure if it can be configured to do it differently.

**Comment by zbalkan** [comment]
Hi @vanhecke,

May I ask what problem are you trying to solve?

**Comment by vanhecke** [comment]
Hey @zbalkan  I want to send the logs to a logging platform for security-related analytics that natively supports jsonl.

Sending them in jsonl would require less CPU cycles on both sides.

**Comment by zbalkan** [comment]
So, I guess you already tested using the HTTP target and found that is the bottleneck, right? Can you please let us know about your test setup so that we can reproduce the issue?

Then, we can benchmark if the suggested change solved the issue causing the bottleneck.

**Comment by ksl28** [comment]
@zbalkan 
Having the same issue sending to OpenObserve. The DNS data ends up nested as a JSON string inside MessageTemplate/RenderedMessage, which makes it impossible to query individual fields like clientIp or question.questionName without an intermediate tool like Vector just to unwrap it.
Would be great if the HTTP sink could just POST a flat JSON array of the raw log objects, similar to what the file sink outputs in JSONL. That would make it work natively with most modern log platforms.

**Comment by zbalkan** [comment]
Can you please provide some sample logs for me to understand the issue?

**Comment by ksl28** [comment]
> Can you please provide some sample logs for me to understand the issue?

Here are the sample logs showing the issue. The DNS data ends up as an escaped JSON string inside both messagetemplate and renderedmessage, which are identical. This makes it impossible to query individual fields like clientIp or question.questionName directly without an intermediate tool to unwrap the data first.
```
{"_timestamp":1774362200546445,"level":"Information","messagetemplate":"{\"answers\":[],\"clientIp\":\"10.0.0.50\",\"edns\":[],\"protocol\":\"Udp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"example.com\",\"questionType\":\"A\"},\"responseCode\":\"NoError\",\"responseType\":\"Cached\",\"timestamp\":\"2026-03-24T14:23:18.055Z\"}","renderedmessage":"{\"answers\":[],\"clientIp\":\"10.0.0.50\",\"edns\":[],\"protocol\":\"Udp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"example.com\",\"questionType\":\"A\"},\"responseCode\":\"NoError\",\"responseType\":\"Cached\",\"timestamp\":\"2026-03-24T14:23:18.055Z\"}","timestamp":"2026-03-24T14:23:18.554Z"}
{"_timestamp":1774362200612345,"level":"Information","messagetemplate":"{\"answers\":[],\"clientIp\":\"10.0.0.51\",\"edns\":[],\"protocol\":\"Udp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"test.local\",\"questionType\":\"AAAA\"},\"responseCode\":\"NxDomain\",\"responseType\":\"Authoritative\",\"timestamp\":\"2026-03-24T14:23:19.102Z\"}","renderedmessage":"{\"answers\":[],\"clientIp\":\"10.0.0.51\",\"edns\":[],\"protocol\":\"Udp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"test.local\",\"questionType\":\"AAAA\"},\"responseCode\":\"NxDomain\",\"responseType\":\"Authoritative\",\"timestamp\":\"2026-03-24T14:23:19.102Z\"}","timestamp":"2026-03-24T14:23:19.654Z"}
{"_timestamp":1774362200698765,"level":"Information","messagetemplate":"{\"answers\":[{\"name\":\"example.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":300,\"recordData\":\"93.184.216.34\"}],\"clientIp\":\"10.0.0.52\",\"edns\":[],\"protocol\":\"Tcp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"example.net\",\"questionType\":\"A\"},\"responseCode\":\"NoError\",\"responseType\":\"Recursive\",\"timestamp\":\"2026-03-24T14:23:20.210Z\"}","renderedmessage":"{\"answers\":[{\"name\":\"example.net\",\"recordType\":\"A\",\"recordClass\":\"IN\",\"recordTtl\":300,\"recordData\":\"93.184.216.34\"}],\"clientIp\":\"10.0.0.52\",\"edns\":[],\"protocol\":\"Tcp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"example.net\",\"questionType\":\"A\"},\"responseCode\":\"NoError\",\"responseType\":\"Recursive\",\"timestamp\":\"2026-03-24T14:23:20.210Z\"}","timestamp":"2026-03-24T14:23:20.812Z"}
{"_timestamp":1774362200754321,"level":"Information","messagetemplate":"{\"answers\":[],\"clientIp\":\"10.0.0.53\",\"edns\":[],\"protocol\":\"Udp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"blocked.example\",\"questionType\":\"A\"},\"responseCode\":\"NxDomain\",\"responseType\":\"Blocked\",\"timestamp\":\"2026-03-24T14:23:21.333Z\"}","renderedmessage":"{\"answers\":[],\"clientIp\":\"10.0.0.53\",\"edns\":[],\"protocol\":\"Udp\",\"question\":{\"questionClass\":\"IN\",\"questionName\":\"blocked.example\",\"questionType\":\"A\"},\"responseCode\":\"NxDomain\",\"responseType\":\"Blocked\",\"timestamp\":\"2026-03-24T14:23:21.333Z\"}","timestamp":"2026-03-24T14:23:21.901Z"}
```

**Comment by zbalkan** [comment]
Great. I have an open PR waiting to be merged. I'll try to fix ASAP before merge so that it can be in the next release. Give me some time to analyse it.

**Comment by ksl28** [comment]
> Great. I have an open PR waiting to be merged. I'll try to fix ASAP before merge so that it can be in the next release. Give me some time to analyse it.

Thats impressive 👍 The log exporter idea is awesome, and this will make it great!

**Comment by zbalkan** [comment]
Hi @ksl28,

Here's an example from the new log exporter (see PR https://github.com/TechnitiumSoftware/DnsServer/pull/1580). It has now additional metadata for better SIEM rules/queries as well.

```
{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"toyota.com","questionType":"A"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:08.384Z","meta":{"domainInfo":{"domain":"toyota","topLevelDomain":"com","registrableDomain":"toyota.com","fullyQualifiedDomainName":"toyota.com","topLevelDomainRule":{"name":"com","type":"Normal","labelCount":1,"division":"ICANN"}}}}
,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"toyota.com","questionType":"AAAA"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:08.385Z","meta":{"domainInfo":{"domain":"toyota","topLevelDomain":"com","registrableDomain":"toyota.com","fullyQualifiedDomainName":"toyota.com","topLevelDomainRule":{"name":"com","type":"Normal","labelCount":1,"division":"ICANN"}}}}
,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"toyota.com","questionType":"TXT"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:08.386Z","meta":{"domainInfo":{"domain":"toyota","topLevelDomain":"com","registrableDomain":"toyota.com","fullyQualifiedDomainName":"toyota.com","topLevelDomainRule":{"name":"com","type":"Normal","labelCount":1,"division":"ICANN"}}}}
,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"pfsense.org","questionType":"A"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:09.803Z","meta":{"domainInfo":{"domain":"pfsense","topLevelDomain":"org","registrableDomain":"pfsense.org","fullyQualifiedDomainName":"pfsense.org","topLevelDomainRule":{"name":"org","type":"Normal","labelCount":1,"division":"ICANN"}}}}
,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"pfsense.org","questionType":"AAAA"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:09.804Z","meta":{"domainInfo":{"domain":"pfsense","topLevelDomain":"org","registrableDomain":"pfsense.org","fullyQualifiedDomainName":"pfsense.org","topLevelDomainRule":{"name":"org","type":"Normal","labelCount":1,"division":"ICANN"}}}}
,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"pfsense.org","questionType":"TXT"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:09.804Z","meta":{"domainInfo":{"domain":"pfsense","topLevelDomain":"org","registrableDomain":"pfsense.org","fullyQualifiedDomainName":"pfsense.org","topLevelDomainRule":{"name":"org","type":"Normal","labelCount":1,"division":"ICANN"}}}}
```

The only issue is that the payload is an array of JSON logs, as the issue title asked for, it may be possible to enable `jsonl` instead. I may add a flag to enable jsonl instead. Give me some time.

**Comment by zbalkan** [comment]
It is solved as well. I hope the app gets a review and gets merged into the next release. You can now have the HTTP logs as a JSON array or jsonl/ndjson format.

**Comment by ksl28** [comment]
> Hi [@ksl28](https://github.com/ksl28),
> 
> Here's an example from the new log exporter (see PR [#1580](https://github.com/TechnitiumSoftware/DnsServer/pull/1580)). It has now additional metadata for better SIEM rules/queries as well.
> 
> ```
> {"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"toyota.com","questionType":"A"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:08.384Z","meta":{"domainInfo":{"domain":"toyota","topLevelDomain":"com","registrableDomain":"toyota.com","fullyQualifiedDomainName":"toyota.com","topLevelDomainRule":{"name":"com","type":"Normal","labelCount":1,"division":"ICANN"}}}}
> ,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"toyota.com","questionType":"AAAA"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:08.385Z","meta":{"domainInfo":{"domain":"toyota","topLevelDomain":"com","registrableDomain":"toyota.com","fullyQualifiedDomainName":"toyota.com","topLevelDomainRule":{"name":"com","type":"Normal","labelCount":1,"division":"ICANN"}}}}
> ,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"toyota.com","questionType":"TXT"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:08.386Z","meta":{"domainInfo":{"domain":"toyota","topLevelDomain":"com","registrableDomain":"toyota.com","fullyQualifiedDomainName":"toyota.com","topLevelDomainRule":{"name":"com","type":"Normal","labelCount":1,"division":"ICANN"}}}}
> ,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"pfsense.org","questionType":"A"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:09.803Z","meta":{"domainInfo":{"domain":"pfsense","topLevelDomain":"org","registrableDomain":"pfsense.org","fullyQualifiedDomainName":"pfsense.org","topLevelDomainRule":{"name":"org","type":"Normal","labelCount":1,"division":"ICANN"}}}}
> ,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"pfsense.org","questionType":"AAAA"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:09.804Z","meta":{"domainInfo":{"domain":"pfsense","topLevelDomain":"org","registrableDomain":"pfsense.org","fullyQualifiedDomainName":"pfsense.org","topLevelDomainRule":{"name":"org","type":"Normal","labelCount":1,"division":"ICANN"}}}}
> ,{"answers":[],"clientIp":"127.0.0.1","edns":[],"nameServer":"127.0.0.1","protocol":"Udp","question":{"questionClass":"IN","questionName":"pfsense.org","questionType":"TXT"},"responseCode":"Refused","responseType":"Authoritative","timestamp":"2026-03-26T09:45:09.804Z","meta":{"domainInfo":{"domain":"pfsense","topLevelDomain":"org","registrableDomain":"pfsense.org","fullyQualifiedDomainName":"pfsense.org","topLevelDomainRule":{"name":"org","type":"Normal","labelCount":1,"division":"ICANN"}}}}
> ```
> 
> The only issue is that the payload is an array of JSON logs, as the issue title asked for, it may be possible to enable `jsonl` instead. I may add a flag to enable jsonl instead. Give me some time.


That is freaking awesome! From the top of my head, i believe this resolves my issue 100% 👍 
Great job!

**Comment by ksl28** [comment]
> It is solved as well. I hope the app gets a review and gets merged into the next release. You can now have the HTTP logs as a JSON array or jsonl/ndjson format.

@zbalkan 
It seems its still an issue - but could easily be me, that misunderstood something.
The App is version 3, where can i download the "fix" for this? Or should i edit my config instead?

**Comment by zbalkan** [comment]
Hi @ksl28,

Please see this discussion. 
https://github.com/TechnitiumSoftware/DnsServer/pull/1580#issuecomment-4319817015

**Comment by ksl28** [comment]
> Hi [@ksl28](https://github.com/ksl28),
> 
> Please see this discussion. [#1580 (comment)](https://github.com/TechnitiumSoftware/DnsServer/pull/1580#issuecomment-4319817015)

@zbalkan - from what i understand, version 3.0.1 should have this fix implemented or? Just resetted my forwarder, but its still showing the same symptoms
