### ISSUE TITLE
BUG - Security permissions on Zones broken?

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#1530]
Hi Shreyas,

First, thanks for clustering. Considering the big change, the transition was pretty seamless for me, so thanks for making my life easier. :)

I did find a bug though. On the primary cluster member, if you create a new user and a new group and put that new user in that new group and then add that group to the Zones Permissions with any of the listed permissions it does not work. The zone list simply doesn't show up for the user, no matter the permission. This does work on every other Permissions Section, just not for Zones. If you switch to a secondary cluster member you can then see all the zones. Also, you can even add zones with View only permissions to the secondary cluster members. If you switch back to the primary cluster member, the zones list disappears again.

Since it seems to be a security related issue, I thought best to report it.

Again, thanks for a great product. It's fun watching it mature and using it in a production environment.

Regards,

micush

**Comment by ShreyasZare** [comment]
Thanks for the post. Yes, there are a few issues related to this identified (wont describe them here). Will get them fixed in upcoming update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v14.1 is now available that resolves this issue. Do update and let me know your feedback.

**Comment by micush** [comment]
Hi Shreyas. I've had a go. The security issue seems fixed as I can no longer great zones when I'm not supposed to, but the issue where the zones do not appear is still present:

<img width="1388" height="854" alt="Image" src="https://github.com/user-attachments/assets/657c58c3-5ffb-4698-8650-d73503cca9a6" />

So, half way there.

Regards,

micush

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Do the zones have permission to the user's group? The zones on each node have different permissions so setting permissions on one node does not set it for all nodes.

**Comment by micush** [comment]
I re-tested with your instruction. It works as you describe. It might be
good to have the zone permissions replicated between cluster members so
there's no discrepancy.

**Comment by ShreyasZare** [comment]
The zone level permissions don't sync currently since I am still not sure if that would be desirable since there wont be a way to stop it otherwise. The concern is that if you assign modify permission to a secondary zone then that would also apply to primary zone.

**Comment by micush** [comment]
Thanks for the explanation. Much appreciated.
