### ISSUE TITLE
Extremely high RAM usage after upgrade to 14.1

### ISSUE THREAD

**Issue by aenima99x** [TechnitiumSoftware/DnsServer#1558]
Technitium version 14.1, Running in a Debian LXC (2 vCPU and 12GB RAM) on Proxmox.
Server was running fine with 4GB RAM before the update to 14.1 and then it started maxing out and I had to bump it to 12GB RAM.
LXC has been restarted multiple times with no change, RAM will continually increase to about 7-8GB before leveling out there.

DNS Cache has always been set to save to disk.
Cache max entries was always set to the default 10,000 - I've tried increasing to 100,000 with no changes seen
Enable In-Memory stats has been enabled and no changes seen

Please let me know if I can provide any other info.

<img width="1230" height="118" alt="Image" src="https://github.com/user-attachments/assets/bd866679-ad62-4d7d-919a-5029fdb4cc25" />

<img width="1456" height="746" alt="Image" src="https://github.com/user-attachments/assets/9d0f6611-510d-4fbe-b269-6142f225dcfc" />

<img width="737" height="673" alt="Image" src="https://github.com/user-attachments/assets/5a7e7488-5419-424f-801e-78ec853b2e75" />

**Comment by ShreyasZare** [comment]
Thanks for the post. When the memory usage started maxing out, did you see any issues with the DNS service or any errors in the DNS logs? If yes then let me know the details and post any error logs here. If there were no issues then its nothing to worry about and the memory usage will get back to normal later. Providing more memory to the server will make it consume more as the .NET runtime will cache things and may delay freeing memory. The DNS server runs using .NET runtime which is a garbage collected runtime so used memory gets removed periodically unless its urgently required.

Are you using and DNS Apps? Please share screenshot or list them. 

Do you have block lists configured? Too many lists will make it use more memory and it will increase usage when the server restarts or when the block lists are updated.

**Comment by aenima99x** [comment]
_- When the memory usage started maxing out, did you see any issues with the DNS service or any errors in the DNS logs?_ 
Yes that's how I knew there were issues, all my DNS traffic stopped working and I checked the server and saw it pegged at 100% RAM usage. 

_- Are you using any DNS Apps?_
Nothing besides the SQLite Query Logs

_- Do you have block lists configured?_ 
Yes, lists are below. 

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://adaway.org/hosts.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt


The RAM usage has been bouncing between 6-8GB over the last 24 hours and has not gone down. 
As I noted before these were the exact settings I had in place before upgrading to 14.1 and the RAM usage never went over 2GB. 

Appreciate the quick response, let me know what other info you need.

**Comment by ShreyasZare** [comment]
Thanks for the details. The block lists are fine and too just 200mb when I tried on my setup. The Query Logs app too should not use much memory unless its set to use in-memory db and has high limit set for record retention. 

The only major difference with v14 release is that it uses .NET 9 Runtime which may have some different behavior compared to the .NET 8 runtime being used earlier.

Please share a screenshot of the Dashboard stats (including the stats above the Top Clients table) to that the load on the server is clear and helps understand the issue better. Also share a screenshot of the Settings > Cache section.

**Comment by aenima99x** [comment]
<img width="1132" height="833" alt="Image" src="https://github.com/user-attachments/assets/b0caacd9-8706-4cd4-baff-3474db845045" />
<img width="1132" height="928" alt="Image" src="https://github.com/user-attachments/assets/affbca72-980f-43c8-8236-faf96170509f" />
<img width="1128" height="822" alt="Image" src="https://github.com/user-attachments/assets/93ca4046-6fa9-4aae-b065-4296aa9ba28b" />

Also to note, I'm now seeing higher than normal cpu and very high Disk I/O writes.

<img width="1476" height="716" alt="Image" src="https://github.com/user-attachments/assets/594554b8-dccc-456d-b007-035c3d0ac210" />
<img width="742" height="378" alt="Image" src="https://github.com/user-attachments/assets/aee8e88f-5088-41d4-87a2-84ef8ef717f8" />

**Comment by aenima99x** [comment]
Another follow-up on this. 
I spun up a new LXC with the same specs and then did a docker install of Technitium 14.1. As soon as it started up the RAM immediatley jumped up to using almost all 4GB and the server was almost unusable.
I then spun up another LXC with a docker install but used the 13.6 image and everything is performing as expected. I imported all my zones, dhcp, etc and the RAM usage is sitting right around 200MB.
So there is definitely something with  dotnet 9 that is causing issues here.

**Comment by ShreyasZare** [comment]
Thanks for all the details. The config looks fine. I am not really sure what could be the cause of this issue. I have received a couple of such feedback till now but yet to find a cause.

I would suggest that you give it a try using a VM on proxmox instead of LXC and see if that makes any difference. I have several deployments on VM with just 1GB RAM and the v14 update is roughly using the same amount of memory as that of the previous v13.x release.

**Comment by roswitina** [comment]
I run two Technitium systems on my internal home network on two different Proxmox servers in LXC. Both have the same hardware settings. Ich use Technitium 14.1.

I would like to share this information for informational purposes only. I have allocated 1 GB RAM, 1 core, and 4 GB disk space to the LXC system. I have 805,560 entries in the block lists. The system uses approximately 270 MB RAM and runs smoothly.

![Image](https://github.com/user-attachments/assets/63517e59-b45d-4cdf-9137-a68f15d06fc0)

![Image](https://github.com/user-attachments/assets/91c392b7-ead1-4ef2-8534-b3ba309e5a77)

![Image](https://github.com/user-attachments/assets/eaf8e0d6-397c-4c7f-bda9-cd13618b0397)

**Comment by aenima99x** [comment]
I've been trying to narrow this down and the only common denominator in it that I can find is dotnet9.  
I've tried both Debian13 and Ubuntu25.10 as both LXC and VM and the same issue always appears. As soon as I run the Technitium install script the RAM usage dramatically increases and then eventually maxes out. 
The current install I kept running is a Debian 13.2 LXC running Technitium 14.2
You can see over the last 24 hours that everything is increasing over time and appears like a memory leak.

<img width="1467" height="731" alt="Image" src="https://github.com/user-attachments/assets/1ed728e6-4a8c-4ab2-99ad-e17241101fce" />
<img width="755" height="370" alt="Image" src="https://github.com/user-attachments/assets/fd743a3d-6040-49d0-b77c-1de30207a11a" />

**Comment by 0xChri2** [comment]
Hello,

is this issue fixed in 14.2?

**Comment by aenima99x** [comment]
It was not fixed for me in 14.2. 
I rolled back to 13.6 for the time being, but now I'm even seeing what appears to be a memory leak there also. I really would like to use Technitium since it is a great all-in-one solution for DNS/DHCP but I may need to go back to Unbound, Kea, etc if I can't get this stable.

Here's all the pertinent info -
Proxmox 9.1.1
LXC - 1 CPU, 1GB RAM, 1GB swap, Debian 13.2
Technitium installed with the install script for 13.6

Ram usage over the last 24 hours has gone from an average of 150MB to 500MB and climbing.
I don't see any errors in the logs, but I do see a lot of continual DHCP lease offers. The minimum lease times I have set are 7 days. 

<img width="1467" height="766" alt="Image" src="https://github.com/user-attachments/assets/7ab1e7d4-0bb7-40dc-b82c-a1644a705d1c" />
<img width="726" height="399" alt="Image" src="https://github.com/user-attachments/assets/a44be807-48a0-4001-a19b-7f4ac481a6be" />
<img width="1466" height="655" alt="Image" src="https://github.com/user-attachments/assets/9838fefe-3561-4c57-b4d7-440e39db4116" />

**Comment by aenima99x** [comment]
OK another update. So it looks like it is DHCP causing the issue. After seeing the continual DHCP messages in the logs, I disabled my 4 DHCP scopes as a test. The RAM usage instantly dropped from 550MB to 370 MB and is holding steady there. The Disk I/O also immediately dropped. 

<img width="1465" height="734" alt="Image" src="https://github.com/user-attachments/assets/60beee4c-b14b-47f8-a2ef-1f79c8a830bf" />
<img width="734" height="361" alt="Image" src="https://github.com/user-attachments/assets/424a3e05-71d0-41a8-a5aa-ffefd9140489" />

Here you can see the flat areas are where DHCP scopes are disabled and then re-enabled and they spike again.

<img width="733" height="710" alt="Image" src="https://github.com/user-attachments/assets/814a97ca-6e2f-4da2-9d03-d65b01b8dfcb" />

**Comment by ShreyasZare** [comment]
@aenima99x Thanks for these observations. I will check why DHCP scope is causing this. I have it deployed in production but not seeing similar issues with it though.

**Comment by GitCentre** [comment]
Noob here. 
I have the same issue on a personal Windows 10 machine. Been running it since version 13.6, don't remember seeing high RAM usage, but after updating to 14 or 14.1 RAM usage became anywhere between 2 to 4GB. In v14.1 it used to start with 4GB and then gradually went down to 2GB and never below that. After updating to v14.2 it seems to be always at 2GB.

I use it mainly for blocking and forwarding to other resolvers. I have tried disabling blocking, removed all list links, even deleted the files which I guess wasn't necessary but have no effect on RAM usage. 

Everything else is at default settings. No idea what DHCP Scopes do, tried disabling the default one that was there(as one user mentioned above), no effect on RAM usage whatsoever.

I have restarted the server after making any change, if that matters.

Very useful program BTW, that even a noob like me can use it. Thank you very much for making it.

**Comment by ShreyasZare** [comment]
> Noob here. I have the same issue on a personal Windows 10 machine. Been running it since version 13.6, don't remember seeing high RAM usage, but after updating to 14 or 14.1 RAM usage became anywhere between 2 to 4GB. In v14.1 it used to start with 4GB and then gradually went down to 2GB and never below that. After updating to v14.2 it seems to be always at 2GB.

Thanks for the feedback. My guess till now is that this is due to runtime version change. However, not everyone is observing this issue since it may not be significant for them. My own servers are using roughly same memory that they used with v13.6.

> I use it mainly for blocking and forwarding to other resolvers. I have tried disabling blocking, removed all list links, even deleted the files which I guess wasn't necessary but have no effect on RAM usage.

Removing block lists wont immediately free memory. The DNS server runs over .NET runtime which has garbage collector and it can take a long time to free used memory. It cannot be predicted if it will free memory the next minute or do it in the next hour. Usually if you have memory available on the server, it wont rush to free it immediately.

> Everything else is at default settings. No idea what DHCP Scopes do, tried disabling the default one that was there(as one user mentioned above), no effect on RAM usage whatsoever.
> 
> I have restarted the server after making any change, if that matters.

Restarting will cause the block lists to get loaded in memory again and it uses additional memory while doing this task which may linger for a while before it gets freed. So restarts wont really fix this issue.

> Very useful program BTW, that even a noob like me can use it. Thank you very much for making it.

Thanks for the compliment.

**Comment by rsb-developer** [comment]
Agree, Technitium is super useful and with the clustering, now over the top.  Looking forward to DHCP reservation being added to clustering.  

I am having extremely high RAM usage as well since 14.1.  With 14.1 is was not too bad, but when I upgraded to 14.2 the problem got much worse.  This is a screen capture of the Proxmox LXC where you can see the RAM usage continue to increase, and once RAM is full, CPU goes to 100% and nothing works (DNS or SSH).

<img width="1157" height="657" alt="Image" src="https://github.com/user-attachments/assets/b9271694-7ee7-49a5-93f1-c24ea2c6ce93" />

Only have a few small block lists and the SQL log plugin is not set to use the in-memory db.  I only have a single DHCP scope.  Here is a screen capture showing  the dotnet process with high memory.

<img width="1716" height="704" alt="Image" src="https://github.com/user-attachments/assets/2ee54e01-233a-4edc-b239-72753a16aa7b" />

Let me know if you need any additional information to help narrow down the problem.

I tried to setup Technitium on a new LXC and import the config, but I'm getting an error.  I'll open a new issue on this one.

Thanks again and keep up the good work.

**Comment by ShreyasZare** [comment]
@rsb-developer Thanks for the feedback. If possible, then do export the config and share the zip file with support@technitium.com. This will help me to try to replicate this issue which is otherwise quite tough to figure out.

**Comment by rsb-developer** [comment]
Thanks for the quick reply.

I figured out the issue and I'm not sure how I missed the errors in the logs (maybe I need new glasses)...  I was using the Query Logs (Sqlite) app and at some point post updating to version 14, the sqlite database became corrupted.  With the sqlite db corruption, something is not released and causing unbounded memory usage which will exhaust all memory and hang the VM.

The quick fix was to remove the app (which removed the corrupt db) and restart.  Memory usage is now stable at ~600M.

Is there a way to detect if this (or other exceptions) occurs in the future?  I'm hesitant to re-install Query Logs since it could cause an issue in the future.  Would the other apps have similar issues?

This is a snip from the log file:

[2025-12-20 00:00:07 UTC] System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at TechnitiumLibrary.Net.IPAddressExtensions.ReadFrom(Stream s) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\IPAddressExtensions.cs:line 54
   at TechnitiumLibrary.Net.IPAddressExtensions.ReadFrom(BinaryReader bR) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\IPAddressExtensions.cs:line 36
   at DnsServerCore.Dns.StatsManager.StatCounter..ctor(BinaryReader bR) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\StatsManager.cs:line 1908
   at DnsServerCore.Dns.StatsManager.HourlyStats..ctor(BinaryReader bR) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\StatsManager.cs:line 1644
   at DnsServerCore.Dns.StatsManager.LoadHourlyStats(DateTime dateTime, Boolean forceReload, Boolean ifNotExistsReturnEmptyHourlyStats) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\StatsManager.cs:line 414
[2025-12-20 00:02:39 UTC] [172.31.101.26:45184] [TCP] DNS Server received zone transfer request for zone: cluster-catalog.home
[2025-12-20 00:02:44 UTC] DNS App [Query Logs (Sqlite)]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at QueryLogsSqlite.App.<.ctor>b__17_0(Object state) in Z:\Technitium\Projects\DnsServer\Apps\QueryLogsSqliteApp\App.cs:line 87
   at QueryLogsSqlite.App.<.ctor>b__17_0(Object state) in Z:\Technitium\Projects\DnsServer\Apps\QueryLogsSqliteApp\App.cs:line 87
   at QueryLogsSqlite.App.<.ctor>b__17_0(Object state) in Z:\Technitium\Projects\DnsServer\Apps\QueryLogsSqliteApp\App.cs:line 109

**Comment by ShreyasZare** [comment]
@rsb-developer Good to know that you found the issue and its working stable for you now.

The reason for the sqlite db file to get corrupt is ungraceful shutdown of the DNS server (i.e. process got killed) or due to power loss. Since the Query Logs app is frequently updating the db file, its prone to get the db file corrupt in such cases. 

The other error log you shared is due to corrupt stats file so the stats module is failing to read it. This indicates that you have issue with file corruption in general and its not just the sqlite db file being corrupt.

There is no way that a software can handle such issues to prevent file corruption. So, you have to ensure that the DNS server always shuts down gracefully and that the server has UPS for power backup.

**Comment by trekGriffin** [comment]
> Thanks for the details. The block lists are fine and too just 200mb when I tried on my setup. The Query Logs app too should not use much memory unless its set to use in-memory db and has high limit set for record retention.
> 
> The only major difference with v14 release is that it uses .NET 9 Runtime which may have some different behavior compared to the .NET 8 runtime being used earlier.
> 
> Please share a screenshot of the Dashboard stats (including the stats above the Top Clients table) to that the load on the server is clear and helps understand the issue better. Also share a screenshot of the Settings > Cache section.

I have the same problem until I realize I have the same plugin as you do. Unstalling the Query Logs solved my problem.

**Comment by ShreyasZare** [comment]
@trekGriffin Thanks for sharing your feedback.
