### ISSUE TITLE
DHCP Server

### ISSUE THREAD

**Issue by almapavi** [TechnitiumSoftware/DnsServer#176]
DHCP Server does return an IP when requested from an dhcp relay agents. I have two servers (in migration) in the same network. I disable the scope on Win DHCP server and activate scope on Technitium.  

The Technitium receives the request:

20:40:57.664131 IP (tos 0x0, ttl 64, id 14715, offset 0, flags [DF], proto UDP (17), length 328)
    10.X.X.X.67 > eb0706240f2b.67: BOOTP/DHCP, Request from 4e:29:96:64:da:cd (oui Unknown), length 300, hops 1, xid 0xd74bb579, secs 34, Flags [none]
          Gateway-IP 10.X.X.X
          Client-Ethernet-Address 4e:29:96:64:da:cd (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Parameter-Request Option 55, length 8:
              Subnet-Mask, Classless-Static-Route, Default-Gateway, Domain-Name-Server
              Domain-Name, URL, Option 119, Option 252
            MSZ Option 57, length 2: 1500
            Client-ID Option 61, length 7: ether 4e:29:96:64:da:cd
            Lease-Time Option 51, length 4: 7776000
            Hostname Option 12, length 6: "iPhone"

But it never sends out the IP. Now if I disable the scope on the Technitium and Enable on the Windows Server the client receives a response immediately.

**Comment by ShreyasZare** [comment]
Thanks for the details. I have few queries to understand the scenario better:

- Are you using DHCP Relay Agent which comes with Routing and Remote Access on Windows Server?
- Are both the Win DHCP and Technitium DHCP on the same server?
- Is the IP network in the DHCP scope reachable from the server? If the network is not reachable then any reply to DHCP discover request will be sent out to the Internet.
- Check the logs in Technitium DNS server which will log for DHCP events. Let me know if there are any logs.
- If possible, try to run Wireshark on the server running the DHCP and try to capture packets so that I can see the network activity and understand the issue.
- Just confirm once that any firewall on the server running DHCP has udp 67 port allowed.

**Comment by almapavi** [comment]
**Are you using DHCP Relay Agent which comes with Routing and Remote Access on Windows Server?**
_No, using dhcp relay agent from Sophos Firewall. Clients are Wireless devices on different SSIDs (Each SSID is on a different VLAN)_
**Are both the Win DHCP and Technitium DHCP on the same server?**
_No, two different servers both in the same network space._
**Is the IP network in the DHCP scope reachable from the server? If the network is not reachable then any reply to DHCP discover request will be sent out to the Internet.**
_Sever is reachable as the DNS is working and clients can resolve from that particular server. Note that my Technitium server is acting as secondary DNS and my primary is Windows. The goal is to remove windows once I fix the DHCP_
**Check the logs in Technitium DNS server which will log for DHCP events. Let me know if there are any logs.**
_No log entries what so ever on the Technitium server in regard to DHCP except for confirmation of scope creation - enable/disable of scope._
**If possible, try to run Wireshark on the server running the DHCP and try to capture packets so that I can see the network activity and understand the issue.**
_The capture above is from directly on the Technitium server. The server receives the udp 67 initial request. UDP 67 return (IP lease offer) never happens._
**Just confirm once that any firewall on the server running DHCP has udp 67 port allowed.**
_Yes, I have capture of the FW letting the request out. The capture on the Technitium server confirms the reception_

**Comment by ShreyasZare** [comment]
Thanks for the details. This could be an issue with the DHCP server. It would be great if you can share pcap file for the DHCP messages which will give more details about the discover request. If you dont wish to share it publicly then do send it with an email.

**Comment by ShreyasZare** [comment]
Thanks for the pcap file over email. Found an issue with the DHCP server. There is a validation check which compares source IP with relay agent IP which is causing the issue. Will try to get an update released this weekend.

**Comment by ShreyasZare** [comment]
This issue has been fixed with v5.3 release. Please upgrade to latest version and confirm.

**Comment by almapavi** [comment]
Hi ShreyasZare,
I have upgraded to version 5.3 and still experiencing the issue. Client is not receiving the IP. 

Will send you my captures by email tonight or tomorrow. 

Thanks.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Do share the scope file from the config\scopes folder too with the capture so that I will try to reproduce the issue with same config.

**Comment by ShreyasZare** [comment]
New version 5.4 is now available which fixes this issue. Please reopen this issue if required.
